### ISSUE TITLE
Set order of CV

### ISSUE THREAD

**Issue by phisanti** [mlr-org/mlr3#807] opened 2022-04-22 15:36 UTC
Hi, I am running a parameter optimisation using a custom resampling function. However, I noticed that when I start the tuning instance that although the tuning instance uses the cross-validations blocks that I provide, they come in a different order that I put (see image)

Here is a sample code:

```R
# Create a task 
task = tsk("penguins") 
task$filter(1:50) 
# Instantiate Resampling: 
rc <- rsmp("custom")
rc$instantiate(traintask,   
               list(1:10, 21:30, 41:45), 
               list(11:20, 31:40, 46:50))

measure <- msr("classif.fbeta", na_value = 0)
term_evals <- trm("evals", n_evals = 20)
# Create tuning instance

xgb_learner <- lrn("classif.xgboost",
                  eval_metric = "error",
                  predict_type = "prob")

XGB_parameters <- ps(eta = p_dbl(default = 0.15, lower = 0.1, upper = 0.5))

 instance <- TuningInstanceMultiCrit$new(
  task = task ,
  learner = xgb_learner,
  resampling = rc,
  measure = measure ,
  search_space = XGB_parameters,
  terminator = term_evals )

```

The image is a capture of my actual data, but it is clear that the order of the "iter" seems random rather than linear.
![image](https://user-images.githubusercontent.com/33370667/164745719-75727c49-6bd1-4eaf-b8f6-25a711bddfe4.png)

**Comment by larskotthoff** [comment] 2022-04-22 18:11
Please provide a reproducible example. It looks like there's a typo, the measure, learner, and task are not compatible, and you haven't defined the tuner.

**Comment by phisanti** [comment] 2022-04-22 18:46
This should run properly. Note that there is only three CV sets but the issue stands the same, the groups are selected in a random order (1, 3, 2 ; 2, 3, 1 ; 1, 2, 3) instead of sequentially (1, 2, 3)







```R
library(mlr3)
library(mlr3learners)

# Create a task 
task = tsk("iris") 
# Instantiate Resampling: 
rc <- rsmp("custom")
rc$instantiate(task,   
               list(1:10, 21:30, 41:45), 
               list(11:20, 31:40, 46:50))

measure <- msr("classif.ce")
term_evals <- trm("evals", n_evals = 10)
# Create tuning instance

learner <- lrn("classif.xgboost")

parameters <- ps(eta = p_dbl(lower = 0.001, upper = 0.1))
tuner <- tnr("random_search")

instance <- TuningInstanceMultiCrit$new(
  task = task ,
  learner = learner,
  resampling = rc,
  measure = measure ,
  search_space = parameters,
  terminator = term_evals )
tuner$optimize(instance)

```

**Comment by larskotthoff** [comment] 2022-04-22 22:17
Thanks -- internally, mlr3 uses `future_mapply()`, which, like the base R function `mapply()`, doesn't guarantee any particular order of execution.

What's the use case for needing a particular order?

**Comment by mllg** [comment] 2022-04-23 06:43
The order of execution is randomized for parallelization. This affects only the log output, the result object should be stored in the same order as the custom resampling.

**Comment by mllg** [comment] 2022-04-23 06:46
Admittedly, the log output is a bit confusing here. For longer, parallel calculations, I would suggest to enable progress bars.

**Comment by phisanti** [comment] 2022-04-23 08:13
I thought tha the order of the CV sampling affected the accuracy of predictions as described [here](https://mlr3book.mlr-org.com/optimization.html#nested-resampling). Due to the fact I am dealing with time series signal, I thought I need to input the samples sequentially. Is not that the case?

**Comment by pfistfl** [comment] 2022-04-23 12:00
I think you might require a different resampling strategy alltogether in that case. I am trying to include such strategies in mlr3temporal, perhaps give it a look. It is not really finished though, so there’s a caveat in using it

**Comment by phisanti** [comment] 2022-04-23 12:36
OK, I am trying to implement a by work using the function `tune_nested()`, however, the code does not run because "custom resampling could not be implemented". Here is the change:

```R
rc$instantiate(traintask,     
               list(1:10, 21:30, 41:45), 
               list(11:20, 31:40, 46:50))

# Now understandimg from the diagram in MLR3 book (chapter 4.3) is that the
# outer sampling is a list of index for the inner sampling lists so that they will 
# be selected or at least reserved in that order. Is that correct?

r_out <- rsmp("custom")
r_out$instantiate(traintask,   
               list(1, 2, 3), 
               list(2, 3, 1))

rr <- tune_nested(
  method = "random_search",
  task = traintask,
  learner = xgb_learner,
  inner_resampling = rc,
  outer_resampling = r_out,
  measure = measure,
  search_space = XGB_parameters,
  term_evals = 20)
```

In general, I would be happy if I could reserve the last n rows for calculating the error measure.

**Comment by phisanti** [comment] 2022-04-23 12:48
PS, I noticed the mlr3temporal build status is failing.

**Comment by sebffischer** [comment] 2022-05-11 17:08
The package is currently not actively developed as there is noone who has time

**Comment by phisanti** [comment] 2022-05-16 10:07
@sebffischer oh, that would be a pity as I found lots of useful tools in the package. In that case, it would be useful to mention it on the README page or at least add the "not under maintenance" badger. Hopefully, a backer will come up soon to allocate funding to the project.

**Comment by sebffischer** [comment] 2022-05-16 10:10
@phisanti Ups I think I just spread some misinformation, looks like  @pfistfl is working on it.
What are the exact plans here @pfistfl ? 
And would you be interested in contributing @phisanti ?

**Comment by pfistfl** [comment] 2022-05-16 10:31
Hey, I am currently trying to maintain it on a minimum effort Basis but I am willing to maintain / update things if you see need. 
just raise an issue and ping me if you find any problems with the current package

**Comment by pat-s** [comment] 2022-06-03 14:16
@phisanti Can this issue be closed? To me it looks like your question has been answered by Michel and that there's no issue in the package :)

**Comment by mllg** [comment] 2022-09-09 08:15
Closed as the issue needs to be solved via supporting ordered resamplings.

**Closed by mllg** 2022-09-09 08:15 UTC
