### ISSUE TITLE
[discussion] scope of mlr3

### ISSUE THREAD

**Issue by dselivanov** [mlr-org/mlr3#45] opened 2018-10-06 08:43 UTC
Hi here. I would like to start discussion about mlr3 scope - hope it can be useful for community.

First of all I'm very glad to see that mlr converged to use R6. IMHO there is no need to re-invent the wheel and in R community we need just to leverage design of super-successful scikit-learn. For this reason I've created [mlapi](https://github.com/dselivanov/mlapi) pkg which almost mimics scikit-learn API. I use it in https://github.com/dselivanov/text2vec and https://github.com/dselivanov/rsparse. 

I believe that such core pkg as mlr3 should:

**provide only interface** other pkgs should follow. We have a zoo of pkgs implementing ML algorithms, quality and interfaces vary a lot. I think it is obvious now that the approach taken by caret and mlr was not entirely correct. We can't wrap every useful pkg and re-create API/interface. 

So I believe essentially if pkg aims to be a standard pkg for ML in R there 2 choices:
- implement everything internally as its done in scikit-learn
- provide interface and some utils to help reduce boilerplate coding and let other developers follow it (despite I personally don't like tydyverse it is a good example of how this approach can successfully work)

Use **correct level of abstraction**. Here I strongly believe we have to stick to **matrices** (dense and sparse from `Matrix` pkg) as it's done in scikit-learn. On top of that we may implement "transformers" to construct design matrices from data.frames.

**Comment by berndbischl** [comment] 2018-10-06 09:50
Hi Dmitriy!
It is kinda funny that you are showing up here :) And I am glad, as that saves me one email that I should have written. When we had a meeting about mlr3's design some weeks back, we googled again for some ML packages in R, and saw mlapi. I had the feeling the ideas or maybe better: goals that we (you and us) had were quite similar. I wanted to email you at that point, whether you maybe wanted to join the discussion here, or maybe even contribute.

Also: In a very short time we would like to announce mlr3 on R bloggers so other people could step in or criticize.

**Comment by berndbischl** [comment] 2018-10-06 11:56
> First of all I'm very glad to see that mlr converged to use R6. IMHO there is no need to re-invent the wheel and in R community we need just to leverage design of super-successful scikit-learn

We do not want to reinvent the wheel, exactly the opposite. OTOH we don't want to "blindly" copy over design decisions from other projects. 

In summary: We are looking at a project like sklearn very closely (I also talk to @amueller quite often). If there are good design decisions, we should be MORE aware of, in your opinion, please state them at any point in time. But I also think that *if* sklearn could start fresh, they might also do some things differently. 
Anyway: Lets discuss.

 
> provide only interface

**Comment by berndbischl** [comment] 2018-10-06 12:03
> Use **correct level of abstraction**. Here I strongly believe we have to stick to **matrices** (dense and sparse from `Matrix` pkg) as it's done in scikit-learn. On top of that we may implement "transformers" to construct design matrices from data.frames.

i am really REALLY unsure whether that is correct. and this goes angainst what we currently have. please argue very carefully and in detail here if you really believe that.

**Comment by amueller** [comment] 2018-10-07 15:37
My personal view (and not the view of the sklearn community as a whole) is that users would be better off if sklearn estimators supported dataframes more natively.

Max Kuhn is also working on a new ml API, kind of a successor of carret, that might be interesting to look at.

**Comment by amueller** [comment] 2018-10-07 15:38
https://github.com/topepo/parsnip

**Comment by pfistfl** [comment] 2018-10-12 08:04
Maybe to add on to this:
One of the current weaknesses of `mlr` is IMHO that we can not really use it for purposes like text mining, where we would require **sparse** matrices. (Bag-of-Words etc.)

I think we really should find a solution for this within `mlr3`.

**Comment by dselivanov** [comment] 2018-10-12 08:21
Most of the ML algorithms work with matrices. So the **transformation step data.frame->matrix is almost always mandatory**. And my point is that it should be explicit. 

There are many ways how to encode categorical variables, impute missing values, etc. One example from @pfistfl above - text data. You need to encode it as sparse matrix. And then pass it to some downstream solver which works with matrices.

This is part of modeling and should be reproducible - easy apply to new data. The more details hidden - the more confusion possible.

If there is demand for API  for casual users - this can be build on top. At the end we all need to keep in mind that packages are build not by casual users. The success of such a meta-package depends on the level of adoption across developer community.

**Comment by mllg** [comment] 2018-10-12 11:40
> Most of the ML algorithms work with matrices. So the **transformation step data.frame->matrix is almost always mandatory**. And my point is that it should be explicit.

I agree. However, there are some (important) algorithms which can deal with features being either numeric or factors. This is true for all tree-based methods. Converting to a sparse matrix is feasible here via dummy encoding, but would likely have a negative impact on both prediction performance and computational performance. So I strongly object using matrices as the default format to store data.

I'm not saying that we do not want support for sparse data. This is way the data backend is exchangeable. It took me ~15 mins to prototype a backend for sparse data here: https://github.com/mlr-org/mlr3/tree/sparse_backend

This is not well tested and not completely integrated yet. However, in the future you can tag learning algorithms with "sparse" to automatically handle format conversions.

**Comment by dselivanov** [comment] 2018-10-12 11:50
> However, there are some (important) algorithms which can deal with features being either numeric or factors. This is true for all tree-based methods. 

That's what I meant by "almost all" :-)

**Comment by amueller** [comment] 2018-10-12 15:42
> That's what I meant by "almost all" :-)

These are really important, though! And scikit-learn has a bunch of issues because this is now basically impossible by design. Also, at least in python, there are no column names in matrices, and in most cases it's helpful to have semantic column names.

>Most of the ML algorithms work with matrices. So the transformation step data.frame->matrix is almost always mandatory. And my point is that it should be explicit.

I'm all for explicit. But I don't think being explicit is in conflict with using dataframes. Doing one-hot encoding for example discards which dummy encode the same categorical variable and that makes it basically impossible to do semantically meaningful feature selection afterwards.

**Comment by jangorecki** [comment] 2019-02-19 12:36
I haven't made closer look at mentioned sparse data structure, but while ago I made one built on top of data.table. Simply by storing (sparse) multidimensional data as table modelled in star schema. Access is very fast because table is always sorted. https://gitlab.com/jangorecki/data.cube

Regarding data.table-matrix conversion, I am pretty sure there is a space for improvement here. So far both methods are implemented in R, pushing down to C shouldn't be very difficult, also using parallelism should be possible.

**Comment by Masutani** [comment] 2019-07-24 04:11
Do you plan to do this sparse data support for end 2 end ? If it involves sparse -> dense conversion internally or explicitly outside means memory explosion. So I prefer native support of sparse matrix end 2 end. ScikitLearn supports Sparse DataFrame, how about you also support sparse data.table ?

**Comment by mllg** [comment] 2019-07-24 08:55
> Do you plan to do this sparse data support for end 2 end ? If it involves sparse -> dense conversion internally or explicitly outside means memory explosion. So I prefer native support of sparse matrix end 2 end. 

If the backend stores the data in a sparse format, and the model accepts sparse data, there will be no internal sparse->dense conversion.

However, there is no standard sparse format in R. E.g., while most models support the `Matrix` sparse format, xgboost implements its very own format so a conversion is unavoidable here. 
We could implement a backend especially for xgboost though, but then you would also need to create a task just for xgboost.

> ScikitLearn supports Sparse DataFrame, how about you also support sparse data.table ?

I'm not sure what you have in mind. Do you mean the suggested `data.cube`?

**Comment by dselivanov** [comment] 2019-07-24 08:56
I would disagree. Matrix is the standard

ср, 24 июл. 2019 г., 12:55 Michel Lang <notifications@github.com>:

**Comment by dselivanov** [comment] 2019-07-24 09:18
But having say that I need to point that different models expect input in
CSC or CSR formats... Anyway in R world dgCMatrix is de facto a standard.

ср, 24 июл. 2019 г., 12:56 Dmitriy Selivanov <selivanov.dmitriy@gmail.com>:

**Comment by jangorecki** [comment] 2019-07-24 09:32
If there is standard sparse matrix class then best would be to provide fast C conversion between data.table or matrix to such class. Another thing is that such sparse class (a package) should be lightweight, and be committed to stay lightweight.

**Comment by mllg** [comment] 2019-07-24 09:32
Well, it would be nice to have some sparse data format which can also store categorical features natively. If there would be an inexpensive conversion to dgCMatrix (e.g., after one-hot encoding the categorical features), we could do this on demand and it would be less code to maintain in mlr3.

**Closed** 2021-09-29 08:13 UTC
Labels: Status: In Progress, Type: Question
