### ISSUE TITLE
Parallelized resampling fails when **mlr3spatiotempcv** is attached

### ISSUE THREAD

**Issue by jannes-m** [mlr-org/mlr3#558] opened 2020-10-01 08:43 UTC
Dear mlr-org Team,
this is a rather weird bug, the subsequent code works if one does not attach **mlr3spatiotempcv** or if one runs the code sequentially, i.e., setting `workers = 1` in the future plan. In any case, thanks for this fantastic framework!

``` r
library("mlr3")
library("mlr3learners")
library("mlr3tuning")
library("mlr3spatiotempcv")
library("paradox")
library("future")
library("future.apply")

# define the task
task = tsk("iris")
# define the learner
learner = lrn("classif.kknn")
# define the hyperparameters: here just the no of nbs (k)
tune_ps = ParamSet$new(list(
  ParamInt$new("k", lower = 1, upper = 20)))
at_knn = AutoTuner$new(
  learner = learner,
  resampling = rsmp("cv", folds = 5),
  measure = msr("classif.ce"),
  search_space = tune_ps,
  terminator = trm("evals", n_evals = 5),
  tuner = tnr("grid_search", resolution = 5)
)

resampling_outer = rsmp("repeated_cv", repeats = 5, folds = 5)
# enable parallel processing
future::plan("multiprocess", workers = 4)
progressr::with_progress(expr = {
  rr = resample(task = task,
                learner = at_knn,
                resampling = resampling_outer,
                store_models = TRUE)
})
#> INFO  [10:13:40.807] Applying learner 'classif.kknn.tuned' on task 'iris' (iter 25/25) 
#> INFO  [10:13:42.066] Starting to optimize 1 parameter(s) with '<OptimizerGridSearch>' and '<TerminatorEvals>' 
#> INFO  [10:13:42.118] Evaluating 1 configuration(s) 
#> INFO  [10:13:42.141] Benchmark with 5 resampling iterations 
#> INFO  [10:13:42.214] Applying learner 'classif.kknn' on task 'iris' (iter 2/5) 
#> INFO  [10:13:42.253] Applying learner 'classif.kknn' on task 'iris' (iter 5/5) 
#> INFO  [10:13:42.279] Applying learner 'classif.kknn' on task 'iris' (iter 3/5) 
#> INFO  [10:13:42.305] Applying learner 'classif.kknn' on task 'iris' (iter 1/5) 
#> INFO  [10:13:42.345] Applying learner 'classif.kknn' on task 'iris' (iter 4/5) 
#> INFO  [10:13:42.387] Finished benchmark
#> Error in .__Task__col_roles(self = self, private = private, super = super, : Assertion on 'names of col_roles' failed: Must be a permutation of set {feature,target,name,order,stratum,group,weight}.
```

<sup>Created on 2020-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       Europe/Berlin               
#>  date     2020-10-01                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package          * version    date       lib
#>  assertthat         0.2.1      2019-03-21 [1]
#>  backports          1.1.10     2020-09-15 [1]
#>  bbotk              0.2.1      2020-09-05 [1]
#>  callr              3.4.4      2020-09-07 [1]
#>  checkmate          2.0.0      2020-02-06 [1]
#>  cli                2.0.2      2020-02-28 [1]
#>  codetools          0.2-16     2018-12-24 [2]
#>  colorspace         1.4-1      2019-03-18 [1]
#>  crayon             1.3.4      2017-09-16 [1]
#>  data.table         1.13.0     2020-07-24 [1]
#>  desc               1.2.0      2018-05-01 [1]
#>  devtools           2.3.2      2020-09-18 [1]
#>  digest             0.6.25     2020-02-23 [1]
#>  dplyr              1.0.2      2020-08-18 [1]
#>  ellipsis           0.3.1      2020-05-15 [1]
#>  evaluate           0.14       2019-05-28 [1]
#>  fansi              0.4.1      2020-01-08 [1]
#>  fs                 1.5.0      2020-07-31 [1]
#>  future           * 1.19.1     2020-09-22 [1]
#>  future.apply     * 1.6.0      2020-07-01 [1]
#>  generics           0.0.2      2018-11-29 [1]
#>  ggplot2            3.3.2      2020-06-19 [1]
#>  globals            0.13.0     2020-09-17 [1]
#>  glue               1.4.2      2020-08-27 [1]
#>  gtable             0.3.0      2019-03-25 [1]
#>  highr              0.8        2019-03-20 [1]
#>  htmltools          0.5.0      2020-06-16 [1]
#>  knitr              1.30       2020-09-22 [1]
#>  lgr                0.3.4      2020-03-20 [1]
#>  lifecycle          0.2.0      2020-03-06 [1]
#>  listenv            0.8.0      2019-12-05 [1]
#>  magrittr           1.5        2014-11-22 [1]
#>  memoise            1.1.0      2017-04-21 [1]
#>  mlr3             * 0.7.0      2020-10-01 [1]
#>  mlr3learners     * 0.4.0      2020-09-25 [1]
#>  mlr3measures       0.2.0      2020-06-27 [1]
#>  mlr3misc           0.5.0      2020-08-13 [1]
#>  mlr3spatiotempcv * 0.0.0.9010 2020-10-01 [1]
#>  mlr3tuning       * 0.3.0      2020-09-08 [1]
#>  munsell            0.5.0      2018-06-12 [1]
#>  paradox          * 0.4.0      2020-07-21 [1]
#>  pillar             1.4.6      2020-07-10 [1]
#>  pkgbuild           1.1.0      2020-07-13 [1]
#>  pkgconfig          2.0.3      2019-09-22 [1]
#>  pkgload            1.1.0      2020-05-29 [1]
#>  prettyunits        1.1.1      2020-01-24 [1]
#>  processx           3.4.4      2020-09-03 [1]
#>  progressr          0.6.0      2020-05-19 [1]
#>  ps                 1.3.4      2020-08-11 [1]
#>  purrr              0.3.4      2020-04-17 [1]
#>  R6                 2.4.1      2019-11-12 [1]
#>  remotes            2.2.0      2020-07-21 [1]
#>  rlang              0.4.7      2020-07-09 [1]
#>  rmarkdown          2.3        2020-06-18 [1]
#>  rprojroot          1.3-2      2018-01-03 [1]
#>  scales             1.1.1      2020-05-11 [1]
#>  sessioninfo        1.1.1      2018-11-05 [1]
#>  stringi            1.5.3      2020-09-09 [1]
#>  stringr            1.4.0      2019-02-10 [1]
#>  testthat           2.3.2      2020-03-02 [1]
#>  tibble             3.0.3      2020-07-10 [1]
#>  tidyselect         1.1.0      2020-05-11 [1]
#>  usethis            1.6.3      2020-09-17 [1]
#>  uuid               0.1-4      2020-02-26 [1]
#>  vctrs              0.3.4      2020-08-29 [1]
#>  withr              2.3.0      2020-09-22 [1]
#>  xfun               0.17       2020-09-09 [1]
#>  yaml               2.2.1      2020-02-01 [1]
#>  source                                   
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  Github (mlr-org/mlr3@eb27358)            
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  Github (mlr-org/mlr3spatiotempcv@730ce03)
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.0)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#>  CRAN (R 4.0.2)                           
#> 
#> [1] C:/Users/jannes.muenchow/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.2/library
```

</details>

**Comment by be-marc** [comment] 2020-10-01 10:19
Confirmed. This can be fixed by setting `future.packages = c("mlr3", "mlr3spatiotempcv")` in Line 75 of `resample.R`. I guess that the additional `task_col_roles` `mlr3spatiotempcv` is setting to `Task` in `zzz.R` are not available in the woker sessions and therefore our assertions fail.

**Comment by mllg** [comment] 2020-10-05 19:38
Yep, this one in weird. I'm wondering if it would make sense to create a special spatio temporal task? What are the drawbacks? @pat-s 

For now, I've relaxed the assertion.

**Comment by pat-s** [comment] 2020-10-05 20:24
> I'm wondering if it would make sense to create a special spatio temporal task?

These exist (`TaskClassifST` and `TaskRegrST`). 

I am not sure why `mlr3spatiotempcv` is loaded in the example above since no spatial task is used.
When using a spatial task, everything works.
Nevertheless, this should not happen in general as debugging this is not so easy - and a superfluous library() call can happen quickly.

PS: Why is the console output not suppressed in the following repress @mllg? Is this related to parallelisation?


```r
    library("mlr3")
    library("mlr3learners")
    library("mlr3tuning")
    library("mlr3spatiotempcv")
    library("paradox")
    library("future")
    library("future.apply")

    lgr::get_logger("mlr3")$set_threshold("warn")
    lgr::get_logger("mlr3tuning")$set_threshold("warn")
    lgr::get_logger("bbotk")$set_threshold("warn")

    # define the task
    task <- tsk("ecuador")
    # define the learner
    learner <- lrn("classif.kknn")
    # define the hyperparameters: here just the no of nbs (k)
    tune_ps <- ParamSet$new(list(
      ParamInt$new("k", lower = 1, upper = 20)
    ))
    at_knn <- AutoTuner$new(
      learner = learner,
      resampling = rsmp("cv", folds = 5),
      measure = msr("classif.ce"),
      search_space = tune_ps,
      terminator = trm("evals", n_evals = 5),
      tuner = tnr("grid_search", resolution = 5)
    )

    resampling_outer <- rsmp("repeated_cv", repeats = 5, folds = 5)
    # enable parallel processing
    future::plan("multisession", workers = 4)
    progressr::with_progress(expr = {
      rr <- resample(
        task = task,
        learner = at_knn,
        resampling = resampling_outer,
        store_models = TRUE
      )
    })
    #> INFO  [22:21:21.802]  k classif.ce                                uhash 
    #> INFO  [22:21:21.802]  5  0.2861708 0591f65c-9ac8-48f5-a764-1f7f89b4c9dd 
    #> INFO  [22:21:21.804] Evaluating 1 configuration(s) 
    #> INFO  [22:21:22.015] Result of batch 4: 
    #> INFO  [22:21:22.016]   k classif.ce                                uhash 
    #> INFO  [22:21:22.016]  20  0.2629339 532c4a7e-81b8-43b7-b515-7dba385ee9a0 
    #> INFO  [22:21:22.018] Evaluating 1 configuration(s) 
    #> INFO  [22:21:22.222] Result of batch 5: 
    #> INFO  [22:21:22.223]   k classif.ce                                uhash 
    #> INFO  [22:21:22.223]  10  0.2595592 8e9987f6-2926-4050-83d3-1e8de96cc718 
    #> INFO  [22:21:22.228] Finished optimizing after 5 evaluation(s) 
    #> INFO  [22:21:22.229] Result: 
    #> INFO  [22:21:22.230]   k learner_param_vals  x_domain classif.ce 
    #> INFO  [22:21:22.230]  15          <list[1]> <list[1]>  0.2529752

```

<sup>Created on 2020-10-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

    sessioninfo::session_info()
    #> ─ Session info ───────────────────────────────────────────────────────────────
    #>  setting  value                                 
    #>  version  R version 4.0.3 RC (2020-10-02 r79292)
    #>  os       macOS Big Sur 10.16                   
    #>  system   x86_64, darwin17.0                    
    #>  ui       X11                                   
    #>  language (EN)                                  
    #>  collate  en_US.UTF-8                           
    #>  ctype    en_US.UTF-8                           
    #>  tz       Europe/Berlin                         
    #>  date     2020-10-05                            
    #> 
    #> ─ Packages ───────────────────────────────────────────────────────────────────
    #>  package          * version    date       lib
    #>  assertthat         0.2.1      2019-03-21 [1]
    #>  backports          1.1.10     2020-09-15 [1]
    #>  bbotk              0.2.1      2020-09-05 [1]
    #>  checkmate          2.0.0      2020-02-06 [1]
    #>  cli                2.0.2      2020-02-28 [1]
    #>  codetools          0.2-16     2018-12-24 [1]
    #>  colorspace         1.4-1      2019-03-18 [1]
    #>  crayon             1.3.4.9000 2020-09-04 [1]
    #>  data.table         1.13.0     2020-07-24 [1]
    #>  digest             0.6.25     2020-02-23 [1]
    #>  dplyr              1.0.2      2020-08-18 [1]
    #>  ellipsis           0.3.1      2020-05-15 [1]
    #>  evaluate           0.14       2019-05-28 [1]
    #>  fansi              0.4.1      2020-01-08 [1]
    #>  fs                 1.5.0      2020-07-31 [1]
    #>  future           * 1.19.1     2020-09-22 [1]
    #>  future.apply     * 1.6.0      2020-07-01 [1]
    #>  generics           0.0.2      2018-11-29 [1]
    #>  ggplot2            3.3.2      2020-06-19 [1]
    #>  globals            0.13.0     2020-09-17 [1]
    #>  glue               1.4.2      2020-08-27 [1]
    #>  gtable             0.3.0      2019-03-25 [1]
    #>  highr              0.8        2019-03-20 [1]
    #>  htmltools          0.5.0      2020-06-16 [1]
    #>  knitr              1.30       2020-09-22 [1]
    #>  lgr                0.3.4      2020-03-20 [1]
    #>  lifecycle          0.2.0      2020-03-06 [1]
    #>  listenv            0.8.0      2019-12-05 [1]
    #>  magrittr           1.5        2014-11-22 [1]
    #>  mlr3             * 0.7.0      2020-10-05 [1]
    #>  mlr3learners     * 0.4.0      2020-09-25 [1]
    #>  mlr3measures       0.2.0      2020-06-27 [1]
    #>  mlr3misc           0.5.0      2020-08-13 [1]
    #>  mlr3spatiotempcv * 0.0.0.9010 2020-09-24 [1]
    #>  mlr3tuning       * 0.3.0      2020-09-08 [1]
    #>  munsell            0.5.0      2018-06-12 [1]
    #>  paradox          * 0.4.0      2020-07-21 [1]
    #>  pillar             1.4.6      2020-07-10 [1]
    #>  pkgconfig          2.0.3      2019-09-22 [1]
    #>  progressr          0.6.0      2020-05-19 [1]
    #>  purrr              0.3.4      2020-04-17 [1]
    #>  R.cache            0.14.0     2019-12-06 [1]
    #>  R.methodsS3        1.8.1      2020-08-26 [1]
    #>  R.oo               1.24.0     2020-08-26 [1]
    #>  R.utils            2.10.1     2020-08-26 [1]
    #>  R6                 2.4.1      2019-11-12 [1]
    #>  rematch2           2.1.2      2020-05-01 [1]
    #>  reprex             0.3.0.9001 2020-08-24 [1]
    #>  rlang              0.4.7      2020-07-09 [1]
    #>  rmarkdown          2.4.1      2020-10-02 [1]
    #>  rstudioapi         0.11       2020-02-07 [1]
    #>  scales             1.1.1      2020-05-11 [1]
    #>  sessioninfo        1.1.1      2018-11-05 [1]
    #>  stringi            1.5.3      2020-09-09 [1]
    #>  stringr            1.4.0      2019-02-10 [1]
    #>  styler             1.3.2.9000 2020-07-05 [1]
    #>  tibble             3.0.3      2020-07-10 [1]
    #>  tidyselect         1.1.0      2020-05-11 [1]
    #>  uuid               0.1-4      2020-02-26 [1]
    #>  vctrs              0.3.4      2020-08-29 [1]
    #>  withr              2.3.0      2020-09-22 [1]
    #>  xfun               0.18       2020-09-29 [1]
    #>  yaml               2.2.1      2020-02-01 [1]
    #>  source                            
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  Github (r-lib/crayon@6b3f0c6)     
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.1)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.1)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  Github (mlr-org/mlr3@6a9359b)     
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.3)                    
    #>  local                             
    #>  CRAN (R 4.0.3)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.3)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  Github (tidyverse/reprex@d3fc4b8) 
    #>  CRAN (R 4.0.2)                    
    #>  Github (rstudio/rmarkdown@29aad5e)
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  Github (pat-s/styler@51d5200)     
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.0)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.2)                    
    #>  CRAN (R 4.0.0)                    
    #> 
    #> [1] /Users/pjs/Library/R/4.0/library
    #> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library

</details>

**Comment by jannes-m** [comment] 2020-10-06 10:39
> I am not sure why mlr3spatiotempcv is loaded in the example above since no spatial task is used.

I have only posted the failing part of my code. I wanted to compare the performance of a spatial CV with a non-spatial CV. That is the reason why I have also attached **mlr3spatiotempcv**. I might be wrong, and will try again, but I thought that the parallelized code was also failing when using spatial CV.

**Comment by pat-s** [comment] 2020-10-06 12:08
> I have only posted the failing part of my code. I wanted to compare the performance of a spatial CV with a non-spatial CV. That is the reason why I have also attached mlr3spatiotempcv.

Ah I see 👍 

> but I thought that the parallelized code was also failing when using spatial CV.

This would be interesting, yes.

Given Michel's answer it might now work in both cases? My reprex from yesterday used the latest mlr3 version so it could be that it fails with the current CRAN version?

**Comment by jannes-m** [comment] 2020-10-08 08:10
I have re-installed the mlr3 github version (**mlr3spatiotempcv** only accepted mlr3 0.7.0, and until yesterday only mlr3 0.6.0 was available on CRAN), and now the code is running again without failure. Additionally, I can confirm that the parallelized code also works with a spatial task using **mlr3spatiotempcv**. Thanks a lot!

**Comment by pat-s** [comment] 2020-10-08 08:16
> mlr3spatiotempcv only accepted mlr3 0.7.0

This was possibly triggered by a downstream dependency. But good to know! I'll increase the version req as well to prevent this issue happening to other users.

Thanks for the report!

**Closed by pat-s** 2020-10-08 08:16 UTC
