### ISSUE TITLE
most frequent imputer for factor columns

### ISSUE THREAD

**Issue by B-Seif** [mlr-org/mlr3#460] opened 2020-03-12 15:26 UTC
First, thank you for this wonderful package.
Is there a way to replace the missing values of the factor column by the most frequent value.
An example of use:
  - Learn a model on a dataset that contains a factor column.
  - Be able in the inference phase, to make a prediction even if the data is missing in this column.

I would like to have the opportunity to do this: 

` imp_fact_most_freq     = po("imputeMOSTFREQUENT", param_vals =list(affect_columns = selector_name(my_factor_vars)))`

`encode      = po("encode",  param_vals =list(affect_columns = selector_name(my_factor_vars)))`

`cat_var_processing = imp_fact_most_freq %>>% encode`

**Comment by pfistfl** [comment] 2020-03-12 21:00
If I understand this correctly this will be possible once https://github.com/mlr-org/mlr3pipelines/pull/366 is merged using PipeOpImputeMode

**Comment by berndbischl** [comment] 2020-03-12 22:47
flo is correct, it is "ImputeMode"

**Comment by B-Seif** [comment] 2020-03-13 07:18
Indeed, I m using the `imputenewlelv` in my ` cat_var_processing` graph. If the train dataset contains  `NA` values in some factorial variable (say, var "SEXE" with two levels , `F` and `M`), the  `imputenewlelv` will replace these `NA` values by the the value `.MISSING`, and then the "SEXE" var will have 3 levels. So, the `encode` will not have a problem in the inference step. However, when the train dataset does not contain any `NA` value in the "SEXE" column, the `encode`  cannot encode the column, because it was trained on a 2-level variable (`F` and `M`), whereas when it receives a `NA`, the `imputenewlvl` transforms it into `.MISSING` and the `encode` know nothing about this value.  So, would it be possible to have the equivalent of the [`handle_unknown` parameter in scikitlearn ` OneHotEncoder`?](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

**Comment by pfistfl** [comment] 2020-03-13 07:44
I understand.
 Something that might work for you might be:
```
po("imputenewlvl") %>>%
po("fixfactors") %>>%
po("imputesample")
```

Fixfactors will drop levels that did not exist during train and imputesample will then impute those.
Later on you can switch out imputesample for imputemode.

**Comment by pfistfl** [comment] 2020-03-16 08:24
Closing here, reopen if the problem is not solved.

**Closed by pfistfl** 2020-03-16 08:24 UTC
