### ISSUE TITLE
learner API interface: update_internal

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3#272] opened 2019-07-09 16:03 UTC
allow an online update function. the contract should be that
the model slot is set, and n new data points are passed. 

an online trainable model should now have a (fast) update function available

we also need a property "online_update" 

another option would be to handle this in train_internal, and implement a case that the model should be updated if the model slot is set and not NULL. but these might be confusing and error prone

**Comment by jakob-r** [comment] 2019-07-09 16:45
We can list learners here which learners have such a thing available
- `DiceKriging::update`

**Comment by mllg** [comment] 2021-09-29 14:50
Duplicate of #622

**Closed by mllg** 2021-09-29 14:50 UTC
Labels: Priority: Medium, Status: Available, Type: Enhancement
